config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'admin/index'
  get 'admin/appearance'
  get 'admin/analytics'
  get 'admin/settings'
  patch 'admin/update', to: 'admin#update', as: :admin_update


  get '/:slug', to: 'profiles#show', as: :user

  resources :links, only: %i[create update destroy] do
    patch 'toggle_active', on: :member
  end

  patch '/link_position/:id', to: 'links#update_position', as: :link_position


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "admin#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  layout 'profile'
  def show
    @user = User.find_by(slug: params[:slug].downcase)
    redirect_to root_path and return unless @user

    @links = @user.links.where(active: true).order(position: :asc)
    # ahoy.track 'Viewed Dashboard', user: @user
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper

  def profile_url(user)
    # Need to return the complete URL for the user's profile.
    # Example: http://localhost:3000/username
    Rails.application.routes.url_helpers.user_url(user.username, host: request.base_url)
  end
end

app/views/profiles/_form.html.erb
<%= form_with(model: current_user, url: admin_update_path) do |f| %>
  <%= f.text_field :username, required: true, placeholder: "Username..." %>
  <br />
  <%= f.label :content %>
  <%= f.file_field :content %>
  <br />
  <%= f.text_field :name, placeholder: "Name..." %>
  <br />
  <%= f.text_area :bio, placeholder: "About you..." %>
  <br />
  <%= f.submit "Update", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
<% end %>

app/views/profiles/_link.html.erb
<%# dom_id => link_id %>
<%= turbo_frame_tag dom_id(link) do %>
  <div class="relative h-[57px] border-2 border-white bg-white text-black shadow sm:h-[60px]">
    <%= link_to link.url, target: "__blank", class: "flex size-full items-center justify-center" do %>
      <div class="absolute inset-y-0 left-2 flex items-center justify-center">
        <img
          src="https://assets.production.linktr.ee/5d9848f35051d706f64b037d00ac07aaa5264df7/icons/tabler-icons/school.svg"
          alt=""
          class="w-8"
        />
      </div>
      <div class="text-center text-sm font-medium leading-[1.5] sm:text-base">
        [<%= link.position %>]: <%= link.name %>
      </div>
      <button class="absolute inset-y-0 right-[6px] z-[1] mx-0 my-auto flex size-[40px] items-center justify-center rounded-xl transition hover:bg-black/10 sm:right-[0.5rem] lg:hidden lg:group-hover:flex">
        <svg width="16" height="16" viewBox="0 0 16 16">
          <path
            fill="currentColor"
            stroke="currentColor"
            d="M12.6661 7.33348C12.2979 7.33348 11.9994 7.63195 11.9994 8.00014C11.9994 8.36833 12.2979 8.66681 12.6661 8.66681C13.0343 8.66681 13.3328 8.36833 13.3328 8.00014C13.3328 7.63195 13.0343 7.33348 12.6661 7.33348Z"
          ></path>
          <path
            fill="currentColor"
            stroke="currentColor"
            d="M8.00057 7.33348C7.63238 7.33348 7.3339 7.63195 7.3339 8.00014C7.3339 8.36833 7.63238 8.66681 8.00057 8.66681C8.36876 8.66681 8.66724 8.36833 8.66724 8.00014C8.66724 7.63195 8.36876 7.33348 8.00057 7.33348Z"
          ></path>
          <path
            fill="currentColor"
            stroke="currentColor"
            d="M3.33333 7.33348C2.96514 7.33348 2.66667 7.63195 2.66667 8.00014C2.66667 8.36833 2.96514 8.66681 3.33333 8.66681C3.70152 8.66681 4 8.36833 4 8.00014C4 7.63195 3.70152 7.33348 3.33333 7.33348Z"
          ></path>
        </svg>
      </button>
    <% end %>
  </div>
<% end %>

app/views/profiles/_links.html.erb
<div id="links_container">
  <% links.each do |link| %>
    <%= render partial: "profiles/link", locals: { link: link } %>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="min-h-screen w-screen bg-[#012141] overflow-y-auto">
  <div class="fixed inset-x-0 mx-auto my-2 mt-2.5 grid w-full max-w-[788px] grid-cols-3 items-center rounded-full border border-transparent bg-transparent py-2 pl-3 pr-6 transition duration-150 ease-in-out sm:p-3 sm:pt-4">
    <button class="col-start-3 flex size-[40px] cursor-pointer flex-col items-center justify-center justify-self-end rounded-[50%] border border-[#E2E2E2] bg-[#F0F0F0] text-black transition-colors hover:bg-[#EBEBEB] focus:border-[#D2D2D2] focus:outline-none active:bg-[#E2E2E2] active:text-black">
      <svg width="16" height="16" viewBox="0 0 16 16">
        <path
          fill="black"
          stroke="black"
          d="M12.6661 7.33348C12.2979 7.33348 11.9994 7.63195 11.9994 8.00014C11.9994 8.36833 12.2979 8.66681 12.6661 8.66681C13.0343 8.66681 13.3328 8.36833 13.3328 8.00014C13.3328 7.63195 13.0343 7.33348 12.6661 7.33348Z"
        ></path>
        <path
          fill="black"
          stroke="black"
          d="M8.00057 7.33348C7.63238 7.33348 7.3339 7.63195 7.3339 8.00014C7.3339 8.36833 7.63238 8.66681 8.00057 8.66681C8.36876 8.66681 8.66724 8.36833 8.66724 8.00014C8.66724 7.63195 8.36876 7.33348 8.00057 7.33348Z"
        ></path>
        <path
          fill="black"
          stroke="black"
          d="M3.33333 7.33348C2.96514 7.33348 2.66667 7.63195 2.66667 8.00014C2.66667 8.36833 2.96514 8.66681 3.33333 8.66681C3.70152 8.66681 4 8.36833 4 8.00014C4 7.63195 3.70152 7.33348 3.33333 7.33348Z"
        ></path>
      </svg>
    </button>
  </div>
  <div class="px-4 pb-8 pt-16">
    <div class="mx-auto max-w-[680px]">
      <div>
        <div class="mb-4">
          <% if @user.content.attached? %>
            <% if @user.content.content_type == "image/png" || @user.content.content_type == "image/jpeg" %>
              <%= image_tag(url_for(@user.content), style: "mx-auto block size-24 rounded-full object-contain") %>
            <% else %>
              <%= video_tag(@user.content, controls: "", class: "mx-auto block size-fit rounded-lg aspect-video") %>
            <% end %>
          <% end %>
        </div>
        <div class="mx-3 flex h-[30px] items-center justify-center truncate text-center text-[20px] font-bold leading-6 text-white">
          <%= @user.name %>
        </div>
        <div class="mt-1 px-10 text-center text-sm font-medium leading-[1.5] text-white sm:text-base">
          <%= @user.bio %>
        </div>
        <div class="mt-8">
          <div class="mb-4">
            <div class="text-center font-bold text-white"><%= @user.username %></div>
          </div>
          <div class="mb-4 space-y-4">
            <%= turbo_stream_from "profile_links_#{@user.id}" %>
            <%= render partial: "profiles/links", locals: { links: @links } %>
          </div>
          <div class="flex items-center justify-center pt-[57px]">
            <%= link_to root_path, target: "__blank", class: "relative box-content flex h-12 items-center justify-center rounded-[64px] border-[#C0C8D1] bg-[#C0C8D1] px-4 text-black antialiased outline-none transition duration-75 ease-out hover:!bg-white focus-visible:ring-2 focus-visible:ring-black focus-visible:ring-offset-2" do %>
              <svg
                viewBox="0 0 16 16"
                enableBackground="new 0 0 24 24"
                class="mr-2 size-4"
              >
                <svg
                  width="16"
                  height="16"
                  viewBox="0 0 20 21"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M11.259 4.87786L14.5965 1.44702L16.5336 3.43084L13.0327 6.76832H17.9573V9.52233H13.0094L16.5336 12.9454L14.5965 14.8903L9.81195 10.0825L5.02745 14.8903L3.09031 12.9532L6.6145 9.53011H1.66663V6.76832H6.59116L3.09031 3.43084L5.02745 1.44702L8.36493 4.87786V0H11.259V4.87786ZM8.36493 13.4666H11.259V20.0016H8.36493V13.4666Z"
                    fill="currentColor"
                  ></path>
                </svg>
              </svg>
              <span class="block text-base font-semibold leading-[1.5] tracking-[-.32px]">
                <% if current_user %>
                  Go to your Eazy Links
                <% else %>
                  Create your Eazy Links
                <% end %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>