config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'admin/index'
  get 'admin/appearance'
  get 'admin/analytics'
  get 'admin/settings'
  patch 'admin/update', to: 'admin#update', as: :admin_update


  get '/:slug', to: 'profiles#show', as: :user

  resources :links, only: %i[create update destroy] do
    patch 'toggle_active', on: :member
  end

  patch '/link_position/:id', to: 'links#update_position', as: :link_position


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "admin#index"
end

app/views/admin/_iframe_preview.html.erb
<%= turbo_frame_tag "preview", class: "h-full" do %>
  <iframe src="<%= profile_url(current_user) %>" 
  class="rounded-2xl h-full"
  style="border: 1rem solid #000;
    border-radius: 5%;
    padding: 10px;
    margin: 10px;"
  width="100%" 
  height="100%" 
  frameborder="0" 
  scrolling="yes"></iframe>
<% end %>

app/views/admin/analytics.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin#analytics</h1>
  <p>Find me in app/views/admin/analytics.html.erb</p>
</div>

app/views/admin/appearance.html.erb
<section class="w-full h-screen">
  <div class="grid grid-cols-2 gap-10 h-full">
    <%= render "profiles/form" %>
    <div class="iframe_container">
      <%= render "admin/iframe_preview" %>
    </div>
  </div>
</section>

app/views/admin/index.html.erb
<section class="h-full w-full">
  <div class="grid grid-cols-2 gap-10">
    <div>
      <% if current_user %>
        <%= current_user.email %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>
      <% end %>
      <%= turbo_stream_from "admin_links_#{current_user.id}" %>
      <%= render partial: "links/form", locals: { link: Link.new } %>
      <%= render partial: "links/admin_links", locals: { links: @links } %>
    </div>
    <div class="iframe_container">
      <%= render "admin/iframe_preview" %>
    </div>
  </div>
</section>

app/views/admin/settings.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin#settings</h1>
  <p>Find me in app/views/admin/settings.html.erb</p>
</div>