config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'admin/index'
  get 'admin/appearance'
  get 'admin/analytics'
  get 'admin/settings'
  patch 'admin/update', to: 'admin#update', as: :admin_update


  get '/:slug', to: 'profiles#show', as: :user

  resources :links, only: %i[create update destroy] do
    patch 'toggle_active', on: :member
  end

  patch '/link_position/:id', to: 'links#update_position', as: :link_position


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "admin#index"
end

app/views/shared/_navbar.html.erb
<nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <span class="font-semibold text-xl tracking-tight">Eazy Links</span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow space-x-4">
      <%= link_to "Home", root_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white" %>
      <%= link_to "Appearance", admin_appearance_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white" %>
      <%= link_to "Analytics", admin_analytics_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white" %>
      <%= link_to "Settings", admin_settings_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white" %>
    </div>
    <div>
      <a href="#" class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0">Download</a>
    </div>
  </div>
</nav> 