config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'admin/index'
  get 'admin/appearance'
  get 'admin/analytics'
  get 'admin/settings'
  patch 'admin/update', to: 'admin#update', as: :admin_update


  get '/:slug', to: 'profiles#show', as: :user

  resources :links, only: %i[create update destroy] do
    patch 'toggle_active', on: :member
  end

  patch '/link_position/:id', to: 'links#update_position', as: :link_position


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "admin#index"
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  acts_as_list
  validates :name, presence: true
  validates :url, presence: true
  # If the link's active attribute is nil, set it to false
  before_save :set_active

  after_create_commit :broadcast_create_link
  after_update_commit :replace_all_links
  after_destroy_commit :delete_link


  private

  def set_active
    self.active = false if self.active.nil?
  end

  def broadcast_create_link
    broadcast_append_to "admin_links_#{user_id}",
      target: "links",
      partial: "links/admin_link",
      locals: { link: self }
  end

  def replace_all_links
    replace_links
  end

  def delete_link
    replace_links
  end

  def replace_links
    broadcast_replace_to "profile_links_#{user_id}",
      target: "links_container",
      partial: "profiles/links",
      locals: { links: user.links.where(active: true).order(position: :asc) }

    broadcast_replace_to "admin_links_#{user_id}",
      target: "links",
      partial: "links/admin_links",
      locals: { links: user.links }
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_link, only: %i[update destroy update_position toggle_active]


  def create
    @link = current_user.links.build(link_params)

    if @link.save
      # redirect_to admin_index_path, notice: 'Link was successfully created.'

    else
      redirect_to admin_index_path, notice: 'Link was not created.'
    end
  end

  def update
    if @link.update(link_params)
      redirect_to admin_index_path, notice: 'Link was successfully updated.'
    else
      redirect_to admin_index_path, notice: 'Link was not updated.'
    end
  end

  def destroy
    @link.destroy
    # redirect_to admin_index_path, notice: 'Link was successfully destroyed.'
  end

  def update_position
    position = params.dig(:link, :position).to_i
    @link.insert_at(position)
  end

  def toggle_active
    active_value = params.dig(:link, :active)
    @link.update(active: active_value)
    request.format = :turbo_stream

    respond_to do |format|
      format.html
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('preview', partial: 'admin/preview')
      end
    end
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:name, :url, :active, :position)
  end
end

app/helpers/links_helper.rb
module LinksHelper
  def icon(name, options={})
    options[:title] ||= name.underscore.humanize
    options[:aria] = true
    options[:nocomment] = true
    options[:variant] ||= :outline
    options[:class] = options.fetch(:classes, nil)
    path = options.fetch(:path, "icons/#{options[:variant]}/#{name}.svg")
    icon = path
    inline_svg_tag(icon, options)
  end
end

app/views/links/_admin_link.html.erb
<div class="row link" data-sortable-update-url="<%= link_position_path(link) %>">
  <div class="col-2"></div>
  <div class="col-8">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <%= icon "grip-vertical", variant: "solid", classes: "link_handle" %><%= render partial: "links/inline_name_form", locals: { link: link } %></h5>
        <div class="row">
          <div class="col-8 link-centered">
            <%= render partial: "links/inline_url_form", locals: { link: link } %>
          </div>
          <div class="col-4">
            <%= render "links/link_actions", link: link %>
          </div>
        </div>
        <div class="btn-group btn-group-sm mt-2" role="group" aria-label="...">
          <div>
            <%= link_to "Visit Link", 
              url_for(link.url), 
              class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded", 
              target: "_blank",
              rel: "noopener noreferrer" %>
          </div>
          <div>
            <%= button_to "Delete", link, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded", method: :delete, data: { confirm: "Are you sure?" } %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-2"></div>
</div>

app/views/links/_admin_links.html.erb
<div id="links" 
        data-controller="sortable" 
        data-sortable-resource-name-value="link"
        data-sortable-handle-value=".link_handle">
  <% links.each do |link| %>
    <%= render partial: "links/admin_link", locals: { link: link } %>
  <% end %>
</div>

app/views/links/_copy_toast.html.erb
<div class="copy-button">
  <div class="wrapper">
    <button class="button" type="button" id="copy-button" title="Copy link">
      <div class="content">
        <div class="copy">
          <svg
            width="13"
            height="13"
            viewbox="0 0 13 13"
            fill="none"
            class="icon"
            aria-hidden="true"
            focusable="false"
          >
            <path
              d="M6.0252 3.43935C5.04889 4.41567 5.04889 5.99858 6.0252 6.97489C6.28067 7.23035 6.57766 7.41897 6.89445 7.54074C6.94651 7.87999 6.89573 8.23198 6.7421 8.54639C6.22117 8.38293 5.7309 8.0948 5.3181 7.68199C3.95126 6.31516 3.95126 4.09908 5.3181 2.73225L6.73231 1.31803C8.09914 -0.0488011 10.3152 -0.0488011 11.6821 1.31803C13.0489 2.68487 13.0489 4.90095 11.6821 6.26778L10.2678 7.68199C10.0307 7.91913 9.768 8.11513 9.48861 8.26998C9.53203 7.87284 9.52024 7.4708 9.45324 7.07631C9.48982 7.04376 9.52567 7.00996 9.56074 6.97489L10.9749 5.56067C11.9513 4.58436 11.9513 3.00145 10.9749 2.02514C9.99864 1.04883 8.41573 1.04883 7.43942 2.02514L6.0252 3.43935ZM2.73939 5.32512C2.9765 5.08801 3.23916 4.89203 3.51852 4.73719C3.47511 5.13433 3.48691 5.53637 3.55392 5.93087C3.51736 5.96339 3.48154 5.99718 3.4465 6.03222L2.03228 7.44644C1.05597 8.42275 1.05597 10.0057 2.03228 10.982C3.00859 11.9583 4.59151 11.9583 5.56782 10.982L6.98203 9.56776C7.95834 8.59145 7.95834 7.00853 6.98203 6.03222C6.72654 5.77674 6.42951 5.58811 6.11268 5.46633C6.06063 5.12708 6.11141 4.7751 6.26503 4.46069C6.78601 4.62415 7.27631 4.91229 7.68914 5.32512C9.05597 6.69195 9.05597 8.90803 7.68914 10.2749L6.27492 11.6891C4.90809 13.0559 2.69201 13.0559 1.32518 11.6891C-0.0416599 10.3222 -0.04166 8.10617 1.32518 6.73933L2.73939 5.32512Z"
              fill="currentColor"
            />
          </svg>
          <div>
            Copy Link
          </div>
        </div>
        <div class="copied">Copied</div>
      </div>
    </button>
  </div>
</div>


<script>
// Animation length + extra 200ms to prevent flickering in the end of the animation
const ANIMATE_TIMEOUT = 3000 + 200;

const button = document.getElementById("button");

button.addEventListener("click", event => {
  if (!button.classList.contains("animate")) {
    button.classList.add("animate");
    setTimeout(() => {
      button.classList.remove("animate");
    }, ANIMATE_TIMEOUT);
  }
});

</script>

app/views/links/_form.html.erb
<%= form_with model: link, url: links_path, class: "w-full max-w-lg inline" do |f| %>
  <div class="flex flex-wrap -mx-3 mb-6">
    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
      <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="link_name">
        Name
      </label>
      <%= f.text_field :name, placeholder: "Name", class: "appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>
    <div class="w-full md:w-1/2 px-3">
      <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="user_url">
        URL
      </label>
      <%= f.text_field :url, placeholder: "URL", class: "appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>
  </div>
  <%= f.submit "Create Link", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
<% end %>

app/views/links/_inline_active_toggle_form.html.erb
<turbo-frame id="link_active_toggle_<%= link.id %>">
  <%= form_with model: link, 
                  url: link_path(link), 
                  data: { turbo: true }, format: :turbo_stream do |f| %>
    <%= f.check_box :active, class: "form-check-input", onchange: "this.form.requestSubmit();" %>
  <% end %>
</turbo-frame>

app/views/links/_inline_name_form.html.erb
<turbo-frame id="link_name_<%= link.id %>" data-controller="edit-link">
  <span class="link-text" 
                data-action="click->edit-link#showForm" 
    data-edit-link-target="content"><%= link.name %></span>
  <div class="edit-form hidden" data-edit-link-target="form">
    <%= form_with model: link, 
                  url: link_path(link), 
                  data: { turbo: true } do |f| %>
      <%= f.text_field :name %>
      <%= link_to "Cancel", "", data: {
                    edit_link_target: "Cancel", 
                    action: "click->edit-link#hideForm"},
                    class: "btn btn-secondary" %>
      <%= f.submit "Update", class:"btn btn-primary" %>
    <% end %>
  </div>
</turbo-frame>

app/views/links/_inline_url_form.html.erb
<turbo-frame id="link_url_<%= link.id %>" data-controller="edit-link">
  <span class="link-text" 
                data-action="click->edit-link#showForm" 
    data-edit-link-target="content"><%= link.url %></span>
  <div class="edit-form hidden" data-edit-link-target="form">
    <%= form_with model: link, 
                  url: link_path(link), 
                  data: { turbo: true } do |f| %>
      <%= f.text_field :url %>
      <%= link_to "Cancel", "", data: {
                    edit_link_target: "Cancel", 
                    action: "click->edit-link#hideForm" },
                    class: "btn btn-secondary" %>
      <%= f.submit "Update", class:"btn btn-primary" %>
    <% end %>
  </div>
</turbo-frame>

app/views/links/_link_actions.html.erb
<div class="row justify-content-end">
  <div class="col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-center">
    <%= render partial: "links/share_button", locals: { url: url_for(link.url) } %>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-12 d-flex align-items-center">
    <div class="form-check form-switch custom-switch-center">
      <%#= render partial: "links/admin_active_toggle", locals: { link: link } %>
      <%= render partial: "links/inline_active_toggle_form", locals: { link: link } %>
    </div>
  </div>
</div>

app/views/links/_share_button.html.erb
<div data-controller="clipboard-button">
  <%= link_to url, 
    class: "bg-slate-400 hover:bg-slate-500 text-white font-bold py-2 px-4 rounded",
    data: { 
      clipboard_button_target: "link",
      url: url,
      action: "click->clipboard-button#copy"
    },
    role: "button" do %>
    <span class="" data-clipboard-button-target="share">Share</span> <i class="bi bi-share"></i>
  <% end %>
</div>